apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
        - name: vprofile-app
          image: 637336795945.dkr.ecr.us-east-1.amazonaws.com/vprofile-eks:new
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-credentials # This should be the name of the secret containing ECR credentials